version: "3"

services:
  prodapp:
    environment:
      - production
    build:
      dockerfile: Dockerfile
      context: ./
    stdin_open: true
    container_name: prodapp
    restart: always
    ports:
      - "3000:3000"

